# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inventory.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Inventory(object):
    def setupUi(self, Inventory):
        Inventory.setObjectName("Inventory")
        Inventory.resize(400, 300)
        self.listWidget = QtWidgets.QListWidget(Inventory)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.listWidget.setObjectName("listWidget")
        self.retranslateUi(Inventory)
        QtCore.QMetaObject.connectSlotsByName(Inventory)

    def retranslateUi(self, Inventory):
        _translate = QtCore.QCoreApplication.translate
        Inventory.setWindowTitle(_translate("Inventory", "Inventory"))

